declare module '@websanova/vue-auth';
declare module '@websanova/vue-auth/drivers/auth/bearer';
declare module '@websanova/vue-auth/drivers/http/axios.1.x';
declare module '@websanova/vue-auth/drivers/router/vue-router.2.x';
declare module 'ant-design-vue/lib/locale-provider/nl_BE';
declare module 'ant-design-vue/lib/locale-provider/fr_BE';
declare module 'vue-paypal-checkout';
declare module 'vue-burger-menu';
declare module 'vue-clipboard2';
